# xinitrc
# Contains programs to be run when Xorg is started. 

# Don't beep at me
xset b off

# Disable ThinkPad touchpad
xinput --disable "$(xinput --list | grep Synaptics | awk '{print $6}' | tr -d 'id=')"

# Scroll with ThinkPad middle button in OpenBSD
xinput --set-prop "/dev/wsmouse" "WS Pointer Wheel Emulation" 1
xinput --set-prop "/dev/wsmouse" "WS Pointer Wheel Emulation Button" 2
xinput --set-prop "/dev/wsmouse" "WS Pointer Wheel Emulation Axes" 6 7 4 5

# Start some programs
#picom -e 1 --inactive-opacity-override -i 1 --inactive-dim 0.2 &
dunst &
unclutter --timeout 3 &
batdaemon &
#redshift-gtk &

# Set wallpaper
find ~/.local/share/dotfiles/ -name "*.png" \
    | sort -R \
    | head -1 \
    | xargs feh --no-fehbg --bg-tile \
    || xsetroot -solid '#008080'

# Load Xresources
xrdb -merge ~/.config/xorg/Xresources

# Customize keyboard
setxkbmap -option caps:swapescape
setxkbmap -option compose:ralt

# Set GUI variables
export FVWM_USERDIR="$XDG_CONFIG_HOME/fvwm"
export FVWM_DATADIR="$XDG_DATA_HOME/fvwm"
export GTK2_RC_FILES="$XDG_CONFIG_HOME/gtk-2.0/gtkrc-2.0"
export GTK_THEME="Raleigh-Reloaded"
export GTK_OVERLAY_SCROLLING=0
export QT_QPA_PLATFORMTHEME="qt5ct"

exec fvwm -f ~/.config/fvwm/config
