# xinitrc
# Contains programs to be run when Xorg is started. 

# Don't beep at me
xset b off

# Disable ThinkPad touchpad
xinput --disable "$(xinput --list | grep Synaptics | awk '{print $6}' | tr -d 'id=')"

# Scroll with ThinkPad middle button in OpenBSD
xinput --set-prop "/dev/wsmouse" "WS Pointer Wheel Emulation" 1
xinput --set-prop "/dev/wsmouse" "WS Pointer Wheel Emulation Button" 2
xinput --set-prop "/dev/wsmouse" "WS Pointer Wheel Emulation Axes" 6 7 4 5

# Start some programs
#picom -e 1 --inactive-opacity-override -i 1 --inactive-dim 0.2 &
dunst &
unclutter --timeout 3 &
sxhkd &
batdaemon &
#redshift-gtk &

# Set wallpaper
find ~/.local/share/dotfiles/ -name "*.png" \
    | sort -R \
    | head -1 \
    | xargs feh --no-fehbg --bg-tile \
    || xsetroot -solid '#008080'

# Load Xresources
xrdb -merge ~/.config/xorg/Xresources
xrdb -merge ~/.config/xorg/gruvbox-dark.xres

# Customize keyboard
setxkbmap -option caps:swapescape
setxkbmap -option compose:ralt

exec fvwm -f ~/.config/fvwm/config
